# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" , "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'  # Укажите нужную версию Go

      - name: Build Binary
        run: go build -o dummy-server.bin ./cmd

      - name: Simple Test
        run: |
          ./dummy-server.bin &
          sleep 3
          curl http://localhost:8888
          kill $!

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: binary
          path: ./dummy-server.bin
